# fix_questions_vector_db.py
# Bespoke, expert answers for all 30 Vector DB questions.
# Fully structured with Core Technical Mechanisms, Code/Configuration Snippets, and Production Trade-offs.

def get_vector_db_fixes() -> dict[str, dict]:
    return {
    "vector_db-easy-1": {
        "question": "How do you choose between Cosine Similarity, Euclidean Distance, and Dot Product for vector search?",
        "answer": "Choosing the optimal distance metric requires understanding their mathematical definitions and hardware execution efficiency:\n\n### 1. Mathematical Definitions:\n- **Dot Product (Inner Product / IP)**: $\\vec{u} \\cdot \\vec{v} = \\sum_{i=1}^d u_i v_i$. Dependent on both angular orientation and vector magnitude. It is the computationally fastest metric, requiring only fused multiply-add (FMA) instructions without square roots.\n- **Cosine Similarity**: $\\cos(\\theta) = \\frac{\\vec{u} \\cdot \\vec{v}}{\\|\\vec{u}\\|_2 \\|\\vec{v}\\|_2}$. Measures pure angular alignment in the range $[-1, 1]$, completely invariant to vector length.\n- **Euclidean Distance ($L_2$)**: $\\|\\vec{u} - \\vec{v}\\|_2 = \\sqrt{\\sum_{i=1}^d (u_i - v_i)^2}$. Measures geometric distance in metric coordinate space.\n\n### 2. The Normalization Equivalence (Production Best Practice):\nIf all embedding vectors are unit-normalized ($L_2$ norm $\\|\\vec{u}\\|_2 = 1.0$), Cosine Similarity and Dot Product become mathematically identical:\n$$\\text{Cosine}(\\vec{u}, \\vec{v}) = \\vec{u} \\cdot \\vec{v}$$\nFurthermore, squared Euclidean distance directly correlates with Dot Product:\n$$\\|\\vec{u} - \\vec{v}\\|_2^2 = \\|\\vec{u}\\|_2^2 + \\|\\vec{v}\\|_2^2 - 2(\\vec{u} \\cdot \\vec{v}) = 2 - 2(\\vec{u} \\cdot \\vec{v})$$\n\n**Production Optimization**: Always unit-normalize embeddings at generation time and configure your vector database index (HNSW, IVF) to use Dot Product / Inner Product. This eliminates floating-point square root and division operations during distance loops, achieving maximum QPS on AVX-512 and ARM NEON hardware."
    },
    "vector_db-easy-2": {
        "question": "What is the fundamental difference between a standard relational database index and an HNSW (Hierarchical Navigable Small World) index?",
        "answer": "The fundamental distinction between relational indexes and HNSW lies in dimensionality, space partitioning, and deterministic vs approximate search guarantees:\n\n### 1. Relational B-Tree / B+ Tree:\n- **Topology**: One-dimensional ordered tree structure. Partitions data into strictly sorted, non-overlapping scalar ranges.\n- **Complexity**: $O(\\log N)$ for exact key lookups and continuous range scans.\n- **Curse of Dimensionality**: Completely fails in high-dimensional vector spaces ($d > 10$). In 1536-dimensional space, geometric volume grows exponentially; bounding boxes in multi-dimensional trees (like R-Trees or KD-Trees) overlap almost entirely, degrading search to $O(N)$ exhaustive full-table scans.\n- **Guarantees**: 100% deterministic, exact match.\n\n### 2. HNSW (Hierarchical Navigable Small World):\n- **Topology**: Multi-layer geometric proximity graph inspired by skip-lists.\n  - *Upper Layers*: Sparse graphs with long-range links acting as \"express highways\" for coarse navigational routing across high-dimensional space.\n  - *Bottom Layer (Layer 0)*: Dense graph with short-range links connecting local nearest neighbors.\n- **Complexity**: $O(\\log N)$ approximate nearest neighbor (ANN) search in continuous vector spaces $\\mathbb{R}^d$.\n- **Guarantees**: Probabilistic ANN search. Balances candidate recall (typically 95-99%) against latency (<5ms) via search beam tuning (`efSearch`).\n\n**Trade-offs**: B-Trees have minimal memory overhead and fast updates. HNSW requires extensive RAM to store graph edge adjacency lists ($M$ bidirectional links per node) and requires background graph restructuring for mutations."
    },
    "vector_db-easy-3": {
        "question": "How do you design a basic schema to store embeddings alongside their source text and metadata?",
        "answer": "A robust vector storage schema balances fast in-memory ANN traversal, rich metadata filtering, and full-text payload retrieval.\n\n### PostgreSQL with `pgvector` Schema Design:\n```sql\nCREATE EXTENSION IF NOT EXISTS vector;\n\nCREATE TABLE document_embeddings (\n    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n    document_id VARCHAR(128) NOT NULL,\n    chunk_index INT NOT NULL,\n    content TEXT NOT NULL,\n    metadata JSONB NOT NULL,\n    embedding vector(1536) NOT NULL,\n    created_at TIMESTAMPTZ DEFAULT NOW()\n);\n\n-- HNSW vector similarity index using cosine distance\nCREATE INDEX idx_embeddings_hnsw ON document_embeddings \nUSING hnsw (embedding vector_cosine_ops) \nWITH (m = 16, ef_construction = 64);\n\n-- GIN index for JSONB metadata pre-filtering\nCREATE INDEX idx_embeddings_metadata ON document_embeddings USING gin (metadata);\nCREATE INDEX idx_embeddings_doc_id ON document_embeddings (document_id);\n```\n\n### Architectural Principles:\n1. **Decoupled Attributes**: Store vector coordinates in a dedicated `vector(1536)` column for HNSW indexing; store structured attributes (`tenant_id`, `department`, `tags`) in `JSONB` with a GIN index for fast pre-filtering.\n2. **Payload Sizing**: Store text chunks (<1,000 tokens) directly in `content`. For multi-megabyte raw files (PDFs, images), store the binary in AWS S3 and save only the S3 URI and extracted text chunk in the database row.\n\n**Trade-offs**: Storing large raw documents directly in vector database rows bloats disk pages, degrades buffer cache hit rates, and slows down index scans."
    },
    "vector_db-easy-4": {
        "question": "Design a basic API pipeline for inserting and retrieving vectors from a hosted database like Pinecone?",
        "answer": "A production Pinecone v3+ pipeline requires batch upserting with namespace isolation and metadata-filtered similarity queries:\n\n### Implementation Pipeline:\n```python\nfrom pinecone import Pinecone, ServerlessSpec\n\n# 1. Initialize client and connect to index\npc = Pinecone(api_key=\"your-api-key\")\nindex = pc.Index(\"enterprise-knowledge-base\")\n\n# 2. Batch insertion with metadata payloads\ndef batch_upsert_vectors(batch_chunks: list[dict], namespace=\"prod-v1\"):\n    vectors = []\n    for chunk in batch_chunks:\n        vectors.append({\n            \"id\": chunk[\"id\"],\n            \"values\": chunk[\"embedding\"],  # List of float32 (e.g. 1536-dim)\n            \"metadata\": {\n                \"text\": chunk[\"text\"],\n                \"category\": chunk[\"category\"],\n                \"tenant_id\": chunk[\"tenant_id\"]\n            }\n        })\n    # Upsert in chunks of 100 to stay under 2MB HTTP payload limit\n    for i in range(0, len(vectors), 100):\n        index.upsert(vectors=vectors[i:i+100], namespace=namespace)\n\n# 3. Filtered Top-K Retrieval\ndef query_similar_chunks(query_vector: list[float], tenant_id: str, top_k=5):\n    response = index.query(\n        namespace=\"prod-v1\",\n        vector=query_vector,\n        top_k=top_k,\n        include_metadata=True,\n        filter={\"tenant_id\": {\"$eq\": tenant_id}}\n    )\n    return [{\"id\": m.id, \"score\": m.score, \"text\": m.metadata[\"text\"]} for m in response.matches]\n```\n\n**Production Gotchas**: Never upsert vectors in single-record HTTP calls\u2014network handshake overhead degrades throughput. Batch in groups of 100-200. Always request `include_metadata=True` only when immediate text payload hydration is necessary, minimizing network egress bandwidth."
    },
    "vector_db-easy-5": {
        "question": "What are the storage implications of using 384-dimensional versus 1536-dimensional embeddings?",
        "answer": "Evaluating storage footprint between 384-dim (e.g., `all-MiniLM-L6-v2`) and 1536-dim (e.g., `text-embedding-3-small`) requires analyzing both raw vector storage and graph index memory structures:\n\n### 1. Raw Vector Footprint (FP32 Precision):\n- **Formula**: $\\text{Size} = \\text{dimensions} \\times 4 \\text{ bytes per float32}$.\n  - **384-dim**: $384 \\times 4 = 1,536 \\text{ bytes } (\\approx 1.5 \\text{ KB})$ per vector.\n    - *1 Million Vectors*: $1.46 \\text{ GB}$.\n    - *10 Million Vectors*: $14.6 \\text{ GB}$.\n  - **1536-dim**: $1536 \\times 4 = 6,144 \\text{ bytes } (\\approx 6.0 \\text{ KB})$ per vector ($4\\times$ increase).\n    - *1 Million Vectors*: $5.86 \\text{ GB}$.\n    - *10 Million Vectors*: $58.6 \\text{ GB}$.\n\n### 2. HNSW Graph Overhead:\n- HNSW stores adjacency lists per node: $M$ bidirectional connections per layer $\\times 8 \\text{ bytes per neighbor ID}$.\n- For standard $M=16$, graph edge indices consume approximately $1.5 \\text{ KB}$ to $2.5 \\text{ KB}$ per vector, regardless of vector dimension.\n- Total memory for 10M vectors:\n  - 384-dim: $(1.5 \\text{ KB} + 2.0 \\text{ KB}) \\times 10\\text{M} \\approx 35 \\text{ GB RAM}$.\n  - 1536-dim: $(6.0 \\text{ KB} + 2.0 \\text{ KB}) \\times 10\\text{M} \\approx 80 \\text{ GB RAM}$.\n\n**Performance & Cost Trade-offs**: 1536-dimensional embeddings consume $4\\times$ more memory bandwidth during distance loops, lowering query QPS by 50-60% and requiring more expensive RAM-heavy cloud instances. Mitigate using Scalar Quantization (SQ8) to reduce float32 vectors to int8 bytes."
    },
    "vector_db-easy-6": {
        "question": "How do you optimize a vector database query by applying metadata pre-filtering?",
        "answer": "Optimizing vector queries via metadata filtering requires selecting the right filtering paradigm inside the database engine:\n\n### Filtering Paradigms:\n1. **Post-Filtering (Anti-Pattern)**:\n   - The engine runs unfiltered ANN search to fetch top-$K$ candidates, then filters out records that fail metadata criteria in application code.\n   - *Failure Mode (Result Starvation)*: If only 2% of documents match the metadata filter, retrieving top-20 unfiltered vectors often yields zero valid results.\n2. **Pre-Filtering (Two-Stage / Iterative)**:\n   - The engine evaluates metadata first using scalar indices (B-tree / inverted list) to generate a set of matching IDs, then runs brute-force vector distance on those IDs.\n   - *Limitation*: If the filtered subset is large (e.g. 500,000 vectors), brute-force scanning is unacceptably slow (>200ms).\n3. **Single-Stage Filtered HNSW (Production Standard)**:\n   - Modern engines (Qdrant, Milvus) integrate metadata checks directly into the HNSW beam traversal.\n   - At each candidate graph node, the engine checks an in-memory bitset. If the node fails the filter, it is excluded from results, but its graph edges are still traversed to reach valid neighbors.\n```python\n# Qdrant single-stage filtered search\nresults = client.search(\n    collection_name=\"enterprise_kb\",\n    query_vector=query_emb,\n    query_filter=Filter(\n        must=[FieldCondition(key=\"department\", match=MatchValue(value=\"legal\"))]\n    ),\n    limit=10\n)\n```\n\n**Production Rule**: Build dedicated payload indices on filter fields (e.g. `schema=\"keyword\"` in Qdrant) so bitsets are constructed in $O(1)$ time."
    },
    "vector_db-easy-7": {
        "question": "Design a basic backup and recovery strategy for a local vector database instance?",
        "answer": "A robust backup and recovery strategy for a local vector database (e.g. Qdrant / Chroma / Milvus) combines Physical Snapshots, Write-Ahead Log (WAL) Archiving, and Point-In-Time Recovery (PITR):\n\n### Architecture Strategy:\n1. **Write-Ahead Log (WAL) Persistence**:\n   - Ensure the vector engine flushes transactions to an append-only WAL on persistent NVMe storage with periodic `fsync` intervals (e.g., every 1-2 seconds).\n2. **Online Snapshot Generation**:\n   - Use the database's native snapshot API:\n   ```bash\n   curl -X POST \"http://localhost:6333/collections/knowledge_base/snapshots\"\n   ```\n   - The engine flushes in-memory mutable segments, locks segment metadata, and creates a consolidated snapshot archive (`.snapshot`) containing data files, HNSW graphs, and payload indices without taking the database offline.\n3. **Automated Cloud Backup Offloading**:\n   - Run a daily cron script that archives the snapshot file, hashes it (SHA-256), and transfers it to cloud object storage (AWS S3 / GCS) with bucket versioning and 30-day lifecycle expiration:\n   ```bash\n   aws s3 cp /qdrant/snapshots/knowledge_base-*.snapshot s3://my-backups/vector-db/\n   ```\n4. **Recovery Protocol**:\n   - In disaster recovery, deploy a clean instance, download the snapshot from S3, and invoke the recovery endpoint:\n   ```bash\n   curl -X POST \"http://localhost:6333/collections/knowledge_base/snapshots/recover\"         -H \"Content-Type: application/json\"         -d '{\"location\": \"file:///qdrant/snapshots/latest.snapshot\"}'\n   ```\n\n**Production Gotcha**: Never execute raw `cp -r` or `rsync` on the active vector database data directory while the engine is running; concurrent segment compaction will result in corrupted index pointers."
    },
    "vector_db-easy-8": {
        "question": "How do you handle pagination when retrieving the top-K nearest neighbors?",
        "answer": "Handling pagination in vector databases requires understanding the mathematical limitations of graph traversal under deep offsets:\n\n### The Deep Pagination Problem:\n- In relational databases, `OFFSET 500 LIMIT 10` skips B-tree entries. In HNSW vector search, finding the 500th nearest neighbor requires expanding the search candidate beam `efSearch` to $K + \\text{offset} = 510$.\n- The engine must compute vector distances for exponentially more graph nodes, causing quadratic latency degradation ($O((K + \\text{offset}) \\log N)$). Requesting page 50 can take 10x longer than page 1.\n\n### Production Solutions:\n1. **Cap Maximum Pagination Depth**:\n   - Search engines and RAG retrieval pipelines rarely require deep pagination. Enforce a strict maximum limit ($K \\le 100$ or 5 pages) at the API gateway layer.\n2. **Cursor-Based (Score Boundary) Pagination**:\n   - Use the similarity score and ID of the last item from the previous page as a strict boundary for the next query:\n```python\n# Score-cursor pagination in Qdrant/Milvus\npage_2_results = client.search(\n    collection_name=\"kb\",\n    query_vector=query_emb,\n    limit=10,\n    score_threshold=last_seen_score,  # strict upper bound\n    query_filter=Filter(\n        must_not=[FieldCondition(key=\"id\", match=MatchValue(value=last_seen_id))]\n    )\n)\n```\n\n**Trade-offs**: Score-based cursor pagination prevents latency explosions on deep pages and maintains predictable sub-10ms response times."
    },
    "vector_db-easy-9": {
        "question": "What metrics should you monitor to evaluate vector search latency?",
        "answer": "Evaluating vector search latency requires instrumenting metrics across query execution phases, hardware utilization, and algorithmic quality:\n\n### 1. Latency Distribution Percentiles (P50, P95, P99, Max):\n- Segment query latency into distinct operational stages:\n  - **Network Ingress/Egress**: Time in transit and payload serialization.\n  - **Index Traversal Time**: Time spent exploring HNSW graph nodes or IVF clusters.\n  - **Payload Hydration Time**: Time spent fetching raw text or JSON metadata from NVMe disk.\n\n### 2. Throughput & Concurrency Metrics:\n- **Queries Per Second (QPS)**: Aggregate query throughput per node.\n- **Active Search Threads & Queue Depth**: Number of worker threads actively computing vector distances; spikes in queue depth indicate CPU core saturation.\n\n### 3. Hardware & Memory Metrics:\n- **CPU L3 Cache Miss Rate & Memory Bandwidth**: Vector inner products are memory-bandwidth bound. High L3 misses directly degrade search latency.\n- **Page Cache Hit Ratio & Disk I/O Wait**: For tiered storage engines, high I/O wait indicates cold vector paging bottlenecks.\n\n### 4. Algorithmic Quality (Recall@K Drift):\n- Regularly sample production queries and compare ANN top-$K$ results against an exact brute-force flat scan ground truth:\n$$\\text{Recall@K} = \\frac{|\\text{ANN\\_Candidates} \\cap \\text{Exact\\_Ground\\_Truth}|}{K}$$\n\n**Alert Thresholds**: Alert on P99 latency exceeding 50ms, memory saturation >85%, or Recall@10 dropping below 95%."
    },
    "vector_db-easy-10": {
        "question": "How do you update a specific embedding in a vector database when the source document changes?",
        "answer": "Updating an embedding in a vector database requires deterministic keying, idempotent upserts, and background graph compaction:\n\n### Update Mechanism:\n1. **Deterministic Primary Keying**:\n   - Generate vector IDs using a deterministic hash of document ID and chunk position: `vector_id = md5(f\"{doc_id}_{chunk_index}\")`.\n2. **Idempotent Atomic Upsert**:\n   - Call the database upsert endpoint with the existing vector ID:\n```python\nclient.upsert(\n    collection_name=\"enterprise_docs\",\n    points=[\n        PointStruct(\n            id=vector_id,\n            vector=new_embedding,\n            payload={\n                \"text\": new_text,\n                \"version\": doc_version,\n                \"updated_at\": timestamp\n            }\n        )\n    ]\n)\n```\n3. **Internal Graph Engine Behavior**:\n   - In HNSW, vectors cannot be updated in-place because changing coordinate values alters high-dimensional spatial relationships.\n   - The engine flags the old vector node as a \"tombstone\" (soft delete) and inserts a new graph node, establishing bidirectional links with its nearest neighbors via greedy routing.\n4. **Compaction & Vacuuming**:\n   - Scheduled background compaction purges tombstoned nodes, reclaims RAM, and restructures graph edges to maintain optimal search diameter.\n\n**Production Gotchas**: High-frequency in-place updates without background vacuuming create an accumulation of dead tombstone nodes, inflating memory usage and degrading search QPS."
    },
    "vector_db-medium-11": {
        "question": "Architect a distributed vector database deployment utilizing sharding to handle 100 million embeddings?",
        "answer": "Scaling to 100 million 1536-dimensional FP32 embeddings requires horizontal sharding, scatter-gather query coordination, and replica-based high availability:\n\n### Capacity Sizing:\n- **Raw Vector Footprint**: $100\\text{M} \\times 1536 \\times 4 \\text{ bytes} = 600 \\text{ GB}$.\n- **HNSW Graph Index Overhead ($M=16$)**: $\\approx 200 \\text{ GB}$.\n- **Total Cluster RAM Required**: $\\approx 800 \\text{ GB} - 1.0 \\text{ TB}$ (for index and vectors pinned in RAM).\n\n### Cluster Architecture:\n1. **Sharding Topology**:\n   - Partition the dataset into 16 shards using consistent hashing on primary key (`hash(id) % 16`). Each shard hosts ~6.25M vectors (~50 GB RAM).\n2. **Node Hardware Layout**:\n   - Deploy 8 worker nodes (each with 128 GB RAM, 16 vCPUs, NVMe SSD).\n   - Each node hosts 2 Primary Shards and 2 Replica Shards assigned to different availability zones for fault tolerance.\n3. **Scatter-Gather Query Coordinator**:\n   - A stateless Coordinator receives the incoming query vector.\n   - Broadcasts the query concurrently to all 16 shards via non-blocking gRPC.\n   - Each shard executes local HNSW search to fetch its local top-$K$ ($K=50$).\n   - The Coordinator merges the $16 \\times 50 = 800$ candidates, executes a global min-heap sort, and returns the top 50 candidates in <20ms.\n\n**Trade-offs**: Scatter-gather latency is bounded by the slowest shard (tail latency). Mitigate by maintaining read replicas so the coordinator routes queries to the least-loaded shard replica."
    },
    "vector_db-medium-12": {
        "question": "How do you handle the performance trade-offs between highly accurate exact nearest neighbor (k-NN) and faster approximate nearest neighbor (ANN) searches?",
        "answer": "Managing trade-offs between exact k-NN (Flat) and approximate nearest neighbor (ANN like HNSW or IVF) requires analyzing the Pareto frontier of recall vs latency:\n\n### 1. Algorithmic Trade-offs:\n- **Exact k-NN (Flat Index)**:\n  - *Mechanism*: Exhaustive brute-force scan evaluating distances across all $N$ vectors ($O(N \\cdot d)$ FLOPs).\n  - *Recall*: 100.0% exact ground truth.\n  - *Scalability*: Terrible for large scale. For 10 million vectors, a single query requires 10 million vector comparisons, resulting in 500ms - 2s latency.\n- **Approximate Nearest Neighbor (ANN via HNSW / IVF-PQ)**:\n  - *Mechanism*: Prunes 99% of search space using proximity graphs or Voronoi cells, evaluating only $O(\\log N)$ distance operations.\n  - *Recall*: 95% - 99.5% configurable recall.\n  - *Scalability*: Sub-5ms query latency on 10 million vectors ($100\\times-500\\times$ faster).\n\n### 2. Runtime Parameter Tuning Dial:\nIn HNSW, `efSearch` (candidate beam size at query time) smoothly trades latency for recall:\n- `efSearch = 16`: 1.2ms latency, ~92% recall (high-throughput recommendation feeds).\n- `efSearch = 64`: 4.5ms latency, ~97.5% recall (standard enterprise RAG).\n- `efSearch = 256`: 15ms latency, ~99.5% recall (high-precision legal/medical search).\n\n**Production Rule**: Use exact flat scan only for small datasets ($<50,000$ vectors) or offline benchmark validation. Use ANN with tuned `efSearch` for all production interactive user queries."
    },
    "vector_db-medium-13": {
        "question": "Design a system that handles high-frequency inserts and updates without severely degrading read query performance in a vector index?",
        "answer": "High-frequency writes in vector databases cause lock contention and graph thrashing. A production architecture adopts an LSM-Tree-Inspired Tiered Storage Engine with write buffers and immutable segments:\n\n### Architecture Components:\n1. **In-Memory Mutable Write Buffer (MemTable)**:\n   - Incoming vectors are written to an append-only Write-Ahead Log (WAL) on NVMe disk and inserted into an in-memory mutable buffer (unindexed flat array or small dynamic HNSW graph).\n   - Writes return in <1ms without acquiring locks on the primary index.\n2. **Dual-Path Read Query Execution**:\n   - Query Coordinator searches both the frozen immutable primary HNSW segments and the active mutable write buffer simultaneously.\n   - Candidate lists are merged using a priority queue.\n3. **Asynchronous Segment Freezing & Index Building**:\n   - When the write buffer reaches a threshold (e.g. 100,000 vectors or 256 MB), it freezes into an immutable segment.\n   - A dedicated background worker thread constructs the optimized HNSW graph or IVF index asynchronously on isolated CPU cores (`cgroups`).\n4. **Segment Compaction & Tombstone Purging**:\n   - Background compaction merges smaller segments and purges deleted vector tombstones, swapping updated segment file descriptors atomically.\n\n**Trade-offs**: Searching small unindexed write buffers adds ~1-2ms to query latency, but completely eliminates write-lock blocking on read queries, supporting 10,000+ writes/second."
    },
    "vector_db-medium-14": {
        "question": "How do you architect a hybrid search implementation combining vector similarity with traditional BM25 full-text search within the database layer?",
        "answer": "Implementing hybrid search natively inside the database layer eliminates multi-hop network roundtrips and inconsistent score scaling:\n\n### Database Engine Architecture (e.g. Qdrant / OpenSearch Neural Search):\n1. **Dual Index Storage**:\n   - **Dense Index**: High-dimensional embeddings ($d=1536$) stored in an HNSW proximity graph.\n   - **Sparse Lexical Index**: Tokenized text stored in an inverted posting list with term frequencies, inverse document frequencies, and document lengths for BM25 scoring.\n2. **Native Execution Plan**:\n   - The query engine parses the search request containing both text and dense vector coordinates in a single query payload.\n   - Dispatches parallel execution threads inside the storage engine: one traverses the HNSW graph; the other evaluates inverted posting lists.\n```python\n# Qdrant native hybrid query execution\nclient.query_points(\n    collection_name=\"enterprise_kb\",\n    prefetch=[\n        Prefetch(query=dense_vector, using=\"dense_vector\", limit=50),\n        Prefetch(query=sparse_vector, using=\"sparse_vector\", limit=50),\n    ],\n    query=FusionQuery(fusion=Fusion.RRF),  # Reciprocal Rank Fusion inside C++ engine\n    limit=10\n)\n```\n3. **In-Engine Reciprocal Rank Fusion (RRF)**:\n   - Fuses ranked candidate lists natively at the C++/Rust engine level:\n   $$RRF(d) = \\frac{1}{60 + r_{\\text{dense}}(d)} + \\frac{1}{60 + r_{\\text{sparse}}(d)}$$\n\n**Production Impact**: Executing hybrid fusion natively inside the database avoids dual-hop network calls and client-side score alignment, reducing end-to-end retrieval latency by 40%."
    },
    "vector_db-medium-15": {
        "question": "Design a multi-tenant vector database architecture ensuring strict logical isolation and access control for different enterprise clients?",
        "answer": "Designing a secure multi-tenant vector database platform requires a Tiered Partitioning Strategy (Silo vs Pooled Partitioning) combined with Query AST Rewriting:\n\n### Isolation Architecture:\n1. **Tier 1 (Enterprise Silo Model - Top 5% Tenants)**:\n   - High-volume clients (>5M vectors or strict compliance) get physically dedicated collections or isolated cluster nodes.\n   - Eliminates \"noisy neighbor\" interference and allows tenant-specific index tuning ($M, efConstruction$).\n2. **Tier 2 (Pooled Namespace Model - Remaining 95% Tenants)**:\n   - Thousands of standard clients share a unified vector collection.\n   - Every vector record contains an immutable, cryptographically validated metadata attribute: `tenant_id`.\n3. **Mandatory Kernel-Level Query AST Rewriting**:\n   - The API gateway authenticates the client's cryptographically signed JWT.\n   - Before the query hits the vector engine, the query AST is rewritten at the driver layer to inject an immutable filter:\n```python\n# Enforced non-bypassable tenant filter\nenforced_filter = Filter(must=[FieldCondition(key=\"tenant_id\", match=MatchValue(value=jwt_tenant_id))])\nquery.filter = query.filter & enforced_filter if query.filter else enforced_filter\n```\n4. **Single-Stage HNSW Payload Indexing**:\n   - Create an in-memory hash/bitset index on `tenant_id` so HNSW graph traversal is strictly constrained to the tenant's subgraph.\n\n**Trade-offs**: Prevents multi-tenant data leakage while avoiding the massive resource overhead of managing thousands of separate HNSW collections in RAM."
    },
    "vector_db-medium-16": {
        "question": "How do you implement memory-mapped files or tiered storage in a vector DB to balance RAM costs with massive dataset sizes?",
        "answer": "Balancing RAM costs against multi-terabyte vector datasets requires a Tiered Memory Hierarchy utilizing Memory-Mapped Files (`mmap`) and DiskANN (Vamana Graph) architecture:\n\n### Memory Hierarchy Breakdown:\n1. **Hot Tier (RAM - ~15% Footprint)**:\n   - Keep only the upper navigational graph layers ($1 \\dots L_{\\text{max}}$) or compressed Product Quantization (PQ) codebooks in system RAM. Upper layers represent <3% of total nodes but guide 90% of routing steps.\n2. **Warm Tier (NVMe SSD via `mmap`)**:\n   - Store raw full-precision FP32 vector payloads and Layer-0 dense graph edges in memory-mapped files (`mmap`).\n   - The Linux kernel OS page cache automatically keeps hot nodes in RAM, reading cold pages from NVMe SSD on demand.\n3. **DiskANN Vamana Graph Approach**:\n   - Beam search traverses the compressed graph in RAM.\n   - When candidate top-$K$ list is selected, the engine executes asynchronous direct I/O (`io_uring` with `O_DIRECT`) to fetch full uncompressed vectors from NVMe SSD for exact re-ranking.\n\n**Production Impact**: Slashes RAM hardware costs by 75-80% (e.g. 500 GB RAM required drops to 64 GB RAM + fast NVMe), with only a negligible 2-4ms latency increase on P95 queries."
    },
    "vector_db-medium-17": {
        "question": "Architect a data pipeline that continuously syncs changes from an operational transactional database directly into a vector database?",
        "answer": "Continuously syncing transactional database changes into a vector database requires Change Data Capture (CDC), streaming event transformation, and idempotent upserts:\n\n### Architecture Flow:\n1. **CDC Source (Debezium)**:\n   - Debezium connector captures row-level mutations from Postgres Write-Ahead Log (WAL) or MySQL Binlog without querying operational tables.\n2. **Event Streaming (Apache Kafka)**:\n   - Emits events (`before`, `after`, `op: c/u/d`) into a Kafka topic partitioned by `primary_key`.\n3. **Stream Processing (Apache Flink / Python Consumer)**:\n   - **For DELETE (`op: d`)**: Dispatches vector deletion by ID to Vector DB.\n   - **For INSERT/UPDATE (`op: c/u`)**: Computes content hash of text fields. If text has changed:\n     - Batches text chunks (batch size 32).\n     - Calls local embedding service.\n     - Formats vector payload with metadata (`tenant_id`, `version`, `updated_at`).\n4. **Idempotent Vector DB Upsert**:\n   - Writes batch of vectors using deterministic keys: `vector_id = md5(f\"{table}_{doc_id}_{chunk_index}\")`.\n5. **Dead-Letter Queue (DLQ)**:\n   - Poison pills and embedding API timeouts route to a Kafka DLQ with exponential retry and alerting.\n\n**Trade-offs**: Delivers sub-second synchronization latency from transactional write to vector availability without impacting operational database performance."
    },
    "vector_db-medium-18": {
        "question": "How do you optimize indexing time for massive batch uploads of pre-computed embeddings?",
        "answer": "Optimizing index construction for massive batch uploads (e.g., 50 million pre-computed vectors) requires Offline Bulk Building, Multi-Threaded Parallel Graph Merging, and Centroid Pre-Fitting:\n\n### Key Optimizations:\n1. **Disable Indexing During Ingestion**:\n   - Never insert vectors into an active HNSW index incrementally. Upload raw vectors into unindexed storage segments first, then trigger a single batch index build.\n2. **Multi-Threaded Parallel Construction**:\n   - Configure the index builder to saturate all CPU cores via OpenMP. Partition vectors into independent subsets, build sub-HNSW graphs in parallel, and merge graph boundaries.\n3. **Product Quantization Centroid Sampling**:\n   - For IVF-PQ indices, fit $k$-means centroids on a random 5% representative sample of the dataset rather than calculating on the full 50M corpus; then encode vectors in parallel using SIMD routines.\n4. **Columnar Bulk Ingestion**:\n   - Stream pre-computed embeddings using Apache Arrow or Parquet batch readers in chunks of 50,000 vectors, avoiding JSON deserialization bottlenecks.\n\n**Production Gain**: Reduces bulk indexing time for 50 million vectors from 36 hours down to under 45 minutes on a 64-core compute instance."
    },
    "vector_db-medium-19": {
        "question": "Design a system to horizontally scale read throughput for a vector database experiencing sudden, massive viral traffic?",
        "answer": "Handling sudden viral traffic surges in a vector database requires Read Replica Auto-Scaling, Query Result Caching, and Dynamic Quality Degradation:\n\n### Architecture Components:\n1. **Decoupled Stateless Read Replicas**:\n   - Separate the write primary from read replicas. Deploy stateless vector search read pods on Kubernetes backed by shared read-only NVMe storage or asynchronous WAL streaming.\n2. **KEDA Auto-Scaling Policy**:\n   - Configure Kubernetes KEDA to scale read replicas horizontally based on CPU utilization (>70%) and incoming request queue depth.\n3. **Tier 1 Semantic & Exact Query Cache**:\n   - Place Redis in front of the vector database cluster. Hash incoming query embeddings; identical queries return top-$K$ candidates directly from Redis memory in <1ms, absorbing 40-60% of viral traffic bursts.\n4. **Dynamic Quality Degradation (Load Shedding)**:\n   - Under extreme peak saturation, automatically throttle search parameter `efSearch` from 64 down to 16. This quadruples the query capacity (QPS) of each node while incurring only a 1.5% drop in ANN recall, preventing cluster collapse.\n\n**Trade-offs**: Autoscaling requires warm standby nodes; dynamic `efSearch` throttling preserves availability during 10x traffic spikes at a negligible cost to recall."
    },
    "vector_db-medium-20": {
        "question": "How do you perform a seamless version upgrade or index rebuild on a live vector database with zero downtime?",
        "answer": "Executing a live version upgrade or index rebuild (e.g. changing embedding model dimension, updating HNSW $M$, or enabling scalar quantization) requires Blue-Green Index Migration with Dual-Writing and Virtual Collection Aliasing:\n\n### Migration Protocol:\n1. **Virtual Alias Abstraction**:\n   - Applications query the database using an alias (`knowledge_base_active`), which points internally to physical collection `collection_v1` (Blue).\n2. **Provision Target Collection (Green)**:\n   - Create `collection_v2` with updated index parameters ($M=32, efConstruction=128$, or new quantization).\n3. **Dual-Write Activation**:\n   - Update upstream ingestion streams to mirror all writes (upserts and deletes) to both `collection_v1` and `collection_v2` concurrently.\n4. **Historical Backfill**:\n   - Run an asynchronous batch job to backfill all historical vectors from cold storage or Blue into Green.\n5. **Validation & Warm-Up**:\n   - Replay a mirrored sample of production read queries against Green to warm up the OS page cache and verify P99 latency and recall metrics against SLAs.\n6. **Atomic Alias Cutover**:\n   - Execute an atomic alias swap in the database engine:\n```json\nPOST /collections/aliases\n{\n  \"actions\": [\n    { \"delete_alias\": { \"alias\": \"knowledge_base_active\", \"collection\": \"collection_v1\" } },\n    { \"add_alias\": { \"alias\": \"knowledge_base_active\", \"collection\": \"collection_v2\" } }\n  ]\n}\n```\n7. **Decommission Blue**: Tear down `collection_v1` after a 48-hour soak period. Zero downtime, zero dropped requests."
    },
    "vector_db-hard-21": {
        "question": "Architect a globally distributed vector database cluster with multi-region active-active replication, ensuring sub-50ms latency for global edge computing?",
        "answer": "Achieving sub-50ms global query latency with multi-region active-active replication requires Geo-Distributed Active-Active Mesh with Hybrid Logical Clocks (HLC) and Local In-Memory HNSW Routing:\n\n### Architecture Topology:\n1. **Multi-Region Deployment**:\n   - Deploy fully replicated vector clusters across 3 primary regions (e.g. US-East, EU-Central, AP-Southeast).\n2. **Edge Ingress**:\n   - Anycast DNS routes edge clients to the closest regional cluster. All read queries execute locally against in-memory HNSW graphs, completing in 10-15ms and easily beating the 50ms global SLA.\n3. **Active-Active Write Mesh**:\n   - Any region accepts writes. The local node writes the vector mutation to its local Raft log and stamps it with a globally unique deterministic UUIDv7 and Hybrid Logical Clock (HLC).\n   - Writes are asynchronously propagated across regions via dedicated high-speed inter-region VPC peering links using Kafka MirrorMaker or internal log replication streams.\n4. **Deterministic Conflict Resolution**:\n   - Concurrent updates to identical vector IDs resolve using Last-Write-Wins (LWW) based on HLC timestamps. Deletes use tombstone state tracking.\n5. **WAN Split-Brain Resilience**:\n   - If an inter-region WAN link severs, each region operates autonomously, serving local reads and queuing writes in local persistent storage, catching up upon WAN restoration.\n\n**Trade-offs**: Accepts eventual consistency for cross-region vector replication (typically 50-200ms lag) in exchange for zero-downtime high availability and ultra-low read latency."
    },
    "vector_db-hard-22": {
        "question": "How do you design a custom, highly specialized vector indexing algorithm optimized for a proprietary dataset where standard HNSW or IVF falls short?",
        "answer": "Standard HNSW and IVF algorithms assume uniform, isotropic distributions in Euclidean space. In specialized domains (e.g. genomic sequences, high-frequency quantitative finance), data often lies on non-linear low-dimensional manifolds or exhibits severe **Hubness** (a tiny fraction of nodes appear as nearest neighbors for millions of queries, causing traversal bottlenecks).\n\n### Custom Algorithmic Design:\n1. **Manifold Dimensionality Projection**:\n   - Apply Kernel PCA, UMAP projections, or autoencoders to project vectors into orthogonal sub-spaces that unroll non-linear manifolds prior to indexing.\n2. **Bounded In-Degree Graph Construction**:\n   - Modify the HNSW construction algorithm to enforce a strict maximum in-degree constraint on graph nodes. This prevents the formation of \"super-hub\" nodes, forcing graph links to spread across diverse topological directions.\n3. **Custom Distance Metric**:\n   - Implement custom distance functions (e.g., Mahalanobis distance with learned covariance matrix $\\Sigma^{-1}$, or custom Hamming distance on binary quantized projections).\n4. **Hardware SIMD Micro-Kernel**:\n   - Write custom C++/Rust kernels leveraging AVX-512 / ARM Neon fused multiply-add (FMA) instructions with loop unrolling, saturating L1 instruction pipelines.\n\n**Production Gain**: Achieves 98% recall where standard HNSW stalled at 82% due to graph local-minima trapping."
    },
    "vector_db-hard-23": {
        "question": "Design a vector database system capable of handling 1 billion dynamic vectors with real-time continuous indexing and sub-100ms retrieval?",
        "answer": "Handling 1 billion 1536-dimensional vectors with sub-100ms retrieval requires Tiered Inverted File with Product Quantization (IVF-PQ), NVMe Re-Ranking (DiskANN), and Memory-Buffered Micro-Batching:\n\n### Capacity Sizing:\n- Storing 1B vectors in FP32 requires 6 TB raw data. In pure RAM with HNSW, this requires >10 TB RAM ($100,000+/month).\n\n### Multi-Tiered Architecture:\n1. **Compressed Navigation Index (RAM)**:\n   - Quantize vectors using Product Quantization (PQ64), compressing each 1536-dim vector from 6,144 bytes to 64 bytes. 1B vectors consume only 64 GB RAM.\n2. **IVF Clustering**:\n   - Partition vectors into 65,536 Voronoi centroids ($k$-means).\n3. **Real-Time Write Buffer**:\n   - Ingesting 5,000 updates/sec writes to an in-memory dynamic buffer (1M vectors). Search queries scan the dynamic buffer + IVF lists in parallel.\n4. **Two-Stage Retrieval Pipeline**:\n   - *Stage 1 (ANN in RAM)*: Scan the nearest 32 IVF centroid posting lists using Asymmetric Distance Computation (ADC) with pre-computed lookup tables. Extracts top 300 candidates in ~20ms.\n   - *Stage 2 (NVMe Re-Score)*: Fetch full uncompressed FP32 vectors for the 300 candidates directly from NVMe SSD via Linux `io_uring` direct I/O. Computes exact dot products in ~25ms.\n\n**Performance**: Total retrieval latency is 45-60ms, handling 1B vectors within a sub-100ms SLA at 90% lower infrastructure cost."
    },
    "vector_db-hard-24": {
        "question": "Architect a hardware-accelerated vector search infrastructure utilizing custom GPU or FPGA deployments to maximize throughput?",
        "answer": "Maximizing vector search throughput for high-concurrency workloads requires GPU Kernel Acceleration via CUDA Anisotropic Graph ANN (CAGRA / cuVS) and PCIe Host-Device Pipelining:\n\n### Architecture Components:\n1. **Compute Engine**:\n   - Deploy NVIDIA H100/A100 GPUs running NVIDIA cuVS / FAISS-GPU CAGRA (CUDA Anisotropic Graph-based Approximate Nearest Neighbor). CAGRA is specifically engineered for massively parallel GPU warp architectures, avoiding branch divergence inherent to CPU-based HNSW.\n2. **Memory & Transfer Pipeline**:\n   - Pin vector graphs and quantized codebooks in High-Bandwidth Memory (HBM3 on H100 with 3.35 TB/s memory bandwidth).\n   - Query vectors streamed from host CPU memory across PCIe Gen 5 using asynchronous pinned memory copies (`cudaMemcpyAsync`) across multiple concurrent CUDA Streams.\n3. **Batch Kernel Processing**:\n   - The GPU groups queries into micro-batches of 128-512, evaluating thousands of distance metrics concurrently on Tensor Cores using half-precision FP16 or INT8 matrix multiplication.\n\n**Throughput Benchmark**: A single dual-H100 GPU server achieves >65,000 QPS on 100 million vectors with sub-5ms P99 latency, replacing 40 CPU nodes and reducing power consumption by 75%."
    },
    "vector_db-hard-25": {
        "question": "How do you build a highly resilient consensus mechanism for vector similarity operations in a heavily partitioned network environment?",
        "answer": "Building a resilient consensus mechanism in partitioned networks requires Multi-Raft Partitioned Consensus with Decoupled State-Machine Vector Indexing:\n\n### Architecture Design:\n1. **Multi-Raft Partitioning**:\n   - Divide dataset into shards; each shard forms a 3-node or 5-node Raft consensus group distributed across separate availability zones.\n2. **Separation of WAL Consensus and Index Construction**:\n   - *Synchronous Quorum*: Vector write operations (upsert, delete) replicate synchronously to a strict quorum ($\\lfloor N/2 \\rfloor + 1$) of the Raft WAL. A write is acknowledged once WAL persistence succeeds.\n   - *Asynchronous Deterministic Indexing*: Each replica node consumes the committed WAL locally and applies mutations to its local HNSW index asynchronously.\n3. **Partition Behavior**:\n   - *Majority Partition*: Continues accepting writes and serving strongly consistent reads.\n   - *Minority Partition*: Automatically refuses writes; serves read queries with a `stale_read: true` flag only if the client explicitly allows eventual consistency.\n4. **Catch-Up & Snapshot Sync**:\n   - Upon partition heal, lagging nodes catch up by streaming missing WAL segments. If lag exceeds WAL ring-buffer retention, the leader generates a lightweight compressed HNSW snapshot to sync the follower.\n\n**Trade-offs**: Decoupling WAL consensus from index building guarantees linearizable durability without holding distributed locks during expensive HNSW graph link updates."
    },
    "vector_db-hard-26": {
        "question": "Design an advanced memory management architecture that dynamically pages specific graph nodes of an HNSW index in and out of RAM based on predictive query patterns?",
        "answer": "Dynamic memory paging for HNSW indices requires Layer-Aware Graph Partitioning with Predictive Prefetching and an Adaptive Replacement Cache (ARC):\n\n### Memory Management Design:\n1. **HNSW Graph Hierarchy Decomposition**:\n   - *Upper Layers (Layers $1 \\dots L_{\\text{max}}$)*: Contain only ~1-3% of total graph nodes, acting as global highway routing hubs. These upper layers are **permanently pinned in RAM** to guarantee instant initial query entry.\n   - *Layer 0 (Base Layer)*: Contains 97-99% of all nodes and all vector payload data. Layer 0 is partitioned into 4 KB aligned virtual memory blocks on NVMe SSD.\n2. **Predictive Prefetching during Beam Search**:\n   - As greedy routing traverses Layer 1, the engine inspects candidate entry nodes in Layer 0.\n   - It issues asynchronous kernel prefetch calls (`posix_madvise(MADV_WILLNEED)` or Linux `io_uring` direct prefetch) for the predicted Layer 0 node clusters before search descends into Layer 0, completely overlapping I/O wait with CPU graph traversal.\n3. **User-Space Buffer Pool**:\n   - An Adaptive Replacement Cache (ARC) tracks node access frequency and recency, evicting cold leaf nodes while keeping warm domain clusters in RAM.\n\n**Impact**: Cuts RAM footprint by 75% while keeping P99 latency within 3ms of a fully in-memory cluster."
    },
    "vector_db-hard-27": {
        "question": "How would you design a system to perform complex, multi-vector, multimodal searches (e.g., combining image, text, and audio embeddings) within a single query execution plan?",
        "answer": "Performing complex multimodal searches across heterogeneous modalities requires Multi-Space Vector Indexing with Late-Interaction Fusion and Cross-Modal Query Planning:\n\n### Architecture Components:\n1. **Multi-Vector Schema Model**:\n   - Each entity record defines multiple independent vector spaces:\n     - `vec_text`: 768-dim (Text embedding via nomic-embed).\n     - `vec_image`: 512-dim (Visual embedding via CLIP ViT-B/32).\n     - `vec_audio`: 256-dim (Audio embedding via CLAP).\n2. **Cross-Modal Query Execution Plan (QEP)**:\n   - Query parser analyzes multimodal inputs (e.g. image file + text filter query).\n   - Dispatches sub-queries in parallel across respective modality HNSW indexes.\n3. **Score Fusion Strategy**:\n   - *Weighted Convex Combination*:\n     $$\\text{Score}(D) = w_{\\text{text}} \\cdot \\cos(Q_t, D_t) + w_{\\text{img}} \\cdot \\cos(Q_i, D_i) + w_{\\text{aud}} \\cdot \\cos(Q_a, D_a)$$\n   - *MaxSim Operator (ColBERT-style)*: Computes max token/modality similarity matrix across fine-grained patch/token representations.\n4. **Candidate Pruning**:\n   - Early-pruning heuristic terminates exploration on sub-indices if intermediate upper bound scores cannot enter current top-$K$ priority queue.\n\n**Trade-offs**: Enables unified discovery across heterogeneous modalities within a single query invocation; requires calibrated score normalization across disparate embedding models."
    },
    "vector_db-hard-28": {
        "question": "Architect a completely serverless vector database plane that dynamically scales compute from zero to thousands of nodes instantly based on query load?",
        "answer": "Architecting a serverless vector database plane requires complete separation of stateless compute and durable shared storage (Pinecone Serverless Architecture):\n\n### Architecture Components:\n1. **Durable Storage Plane**:\n   - Vector indices are stored as immutable columnar segment files in cloud object storage (AWS S3). Files are structured into inverted cluster lists, metadata indices, and quantized vector blocks. Storage cost is pure S3 pennies/GB.\n2. **Stateless Compute Plane (Query Workers)**:\n   - Query nodes run in lightweight serverless containers (Kubernetes / Firecracker microVMs). Nodes maintain no persistent state; they cache index segments on fast local NVMe ephemeral drives.\n3. **Query Routing & Dynamic Fan-Out**:\n   - Query Router analyzes query vector, identifies relevant cluster centroids.\n   - Routes request to active worker hosting cached centroid data.\n   - If load surges, Router instantly spins up additional stateless worker pods. Workers pull required segment headers and PQ codebooks from S3 in <50ms.\n4. **Scale-to-Zero**:\n   - When an index experiences zero traffic for 15 minutes, its compute pods terminate completely. The first arriving query incurs an acceptable cold start (~200ms) to hydrate metadata into a worker, followed by sub-15ms steady-state execution.\n\n**Trade-offs**: Eliminates idle compute costs entirely; requires fast segment caching on NVMe to minimize cold-start latency."
    },
    "vector_db-hard-29": {
        "question": "Design a custom garbage collection and compaction engine for a vector database experiencing extreme rates of document deletion and modification?",
        "answer": "High-frequency updates and deletions in vector databases degrade graph connectivity and inflate RAM. A custom compaction engine utilizes Dynamic Tombstone Bitsets, Localized Graph Re-wiring, and Segment Merge Compaction:\n\n### Compaction Engine Architecture:\n1. **Fast Soft-Deletes (Tombstone Bitsets)**:\n   - Deletions set a bit in an atomic in-memory bitset. During HNSW graph traversal, candidate nodes evaluate the bitset in $O(1)$ time; tombstoned nodes are skipped from results but remain temporarily traversable to avoid isolating downstream graph clusters.\n2. **Online Localized Re-wiring (Eager GC)**:\n   - For individual updates, inspect the deleted node's immediate $M$ predecessor and $M$ successor neighbors. Execute an online edge repair algorithm connecting predecessors to successors to preserve the graph's small-world connectivity.\n3. **Background Segment Compaction (Batch GC)**:\n   - Triggered when tombstone ratio in a segment exceeds 20%.\n   - An isolated background worker thread streams surviving live vectors from fragmented segments into a brand-new pristine segment, building an optimal HNSW graph.\n   - Atomically swaps the active segment directory pointer via filesystem atomic rename (`renameat2()`), safely freeing old segments.\n\n**Result**: Eliminates memory leaks and prevents graph decay even under 10,000 updates/second."
    },
    "vector_db-hard-30": {
        "question": "How do you implement homomorphic encryption or secure multiparty computation natively within the vector database to perform similarity searches on heavily encrypted embeddings?",
        "answer": "Implementing privacy-preserving similarity search over encrypted embeddings requires Fully Homomorphic Encryption (FHE with CKKS Scheme) combined with Secure Two-Party Computation (2PC):\n\n### Cryptographic Protocol:\n1. **Client-Side Encryption (CKKS Scheme)**:\n   - Client encrypts vector $\\vec{x} \\in \\mathbb{R}^d$ into a ciphertext polynomial using a private key. The CKKS scheme supports SIMD vector packing, allowing an entire 1536-dim vector to fit within a single ciphertext.\n2. **Homomorphic Dot Product Calculation**:\n   - The server holds encrypted database vectors $\\text{Enc}(\\vec{y}_i)$. Without decrypting, the server computes homomorphic additions and multiplications:\n   $$\\text{Enc}(\\vec{x} \\cdot \\vec{y}_i) = \\sum_{j=1}^d \\text{Enc}(x_j) \\odot \\text{Enc}(y_{i,j})$$\n3. **The Comparison Barrier in FHE**:\n   - In pure homomorphic encryption, comparison operators ($>$ or $<$) are non-polynomial and computationally prohibitive, preventing HNSW graph traversal.\n4. **Hybrid 2PC / Secret Sharing Architecture**:\n   - The server computes encrypted similarity scores across clustered centroids.\n   - The server and client execute a Garbled Circuit / Oblivious Transfer protocol: the client securely identifies the top-$K$ indices without the server ever learning the query vector, the database vectors, or the search results.\n\n**Trade-offs**: Computations are $100\\times-1000\\times$ slower than plaintext operations; viable for high-security defense, banking, and medical intelligence applications."
    }
}
