import json

new_batch = [
    {
        "id": "medium-fabric-61",
        "category": "FABRIC",
        "niche": "Power BI Integration",
        "difficulty": "MEDIUM",
        "question": "What is the primary difference between DirectQuery and Direct Lake in Fabric?",
        "answer": "DirectQuery sends a SQL query to the database engine, forcing the database to compute the result before sending it back, which can be slow. Direct Lake bypasses the SQL engine entirely. Power BI's internal engine reads the raw Parquet/Delta files directly from OneLake into memory on the fly. It offers the massive performance of Import mode without the need to actually duplicate/import the data."
    },
    {
        "id": "medium-fabric-62",
        "category": "FABRIC",
        "niche": "Power BI Integration",
        "difficulty": "MEDIUM",
        "question": "When does Direct Lake 'fallback' to DirectQuery?",
        "answer": "Direct Lake will silently fallback to standard DirectQuery if a query exceeds capacity limits, if the Delta table has certain unoptimized features (like external shortcuts that lose metadata sync), or if complex Row-Level Security (RLS) is defined directly in the SQL Endpoint rather than natively within Power BI."
    },
    {
        "id": "medium-fabric-63",
        "category": "FABRIC",
        "niche": "Data Integration",
        "difficulty": "MEDIUM",
        "question": "How do you migrate an existing Azure Data Factory (ADF) pipeline to Fabric?",
        "answer": "Currently, there is no one-click migration tool. You must recreate the pipelines in Fabric Data Factory. However, because the underlying JSON definition schema for Copy Activities and Data Flows is nearly identical between Azure and Fabric, you can often copy/paste the JSON payload from the ADF authoring UI directly into the Fabric pipeline JSON editor, needing only to update the Linked Services."
    },
    {
        "id": "medium-fabric-64",
        "category": "FABRIC",
        "niche": "Data Integration",
        "difficulty": "MEDIUM",
        "question": "What is the 'Web Activity' in Fabric Pipelines?",
        "answer": "The Web Activity allows a pipeline to make standard REST API calls (GET, POST, PUT, DELETE) to any external web service. It is commonly used to trigger third-party jobs, authenticate and fetch temporary access tokens, or post status messages to Microsoft Teams or Slack channels upon pipeline completion."
    },
    {
        "id": "medium-pbi-83",
        "category": "POWER BI",
        "niche": "Performance Tuning",
        "difficulty": "MEDIUM",
        "question": "What is the Performance Analyzer in Power BI Desktop?",
        "answer": "The Performance Analyzer is a built-in tool that records how long each visual on a page takes to render. It breaks down the total time into three components: DAX Query time (how long VertiPaq took), Visual Display time (how long the UI took to draw), and Other time (waiting in queue). It allows you to extract the exact DAX query generated by the visual for further tuning in DAX Studio."
    },
    {
        "id": "medium-pbi-84",
        "category": "POWER BI",
        "niche": "Performance Tuning",
        "difficulty": "MEDIUM",
        "question": "Why is high Cardinality bad for Power BI models?",
        "answer": "Cardinality refers to the number of distinct unique values in a column. The VertiPaq engine compresses data heavily using Dictionary encoding and Value encoding. A column with extremely high cardinality (like a unique GUID, Timestamp with milliseconds, or a primary key in a massive Fact table) cannot be compressed effectively, causing the dataset memory footprint to explode and queries to run slowly."
    },
    {
        "id": "medium-pbi-85",
        "category": "POWER BI",
        "niche": "Security",
        "difficulty": "MEDIUM",
        "question": "How do you implement Dynamic Row-Level Security (RLS)?",
        "answer": "Dynamic RLS filters data based on the user currently viewing the report. You create a security table mapping UserPrincipalName (email) to specific dimensions (like Region). In the Manage Roles DAX filter, you use the `USERPRINCIPALNAME()` function to filter the security table. The relationship between the security table and the Fact table then automatically filters the data the user is allowed to see."
    },
    {
        "id": "medium-pbi-86",
        "category": "POWER BI",
        "niche": "Security",
        "difficulty": "MEDIUM",
        "question": "What is Object-Level Security (OLS) in Power BI?",
        "answer": "While RLS hides specific rows of data, OLS completely hides entire tables or specific columns from unauthorized users. If a user without permission views a report containing a visual built on an OLS-secured column, the visual will display an error, preventing them from even knowing the column exists. It requires Tabular Editor to configure."
    },
    {
        "id": "medium-pbi-87",
        "category": "POWER BI",
        "niche": "DAX Advanced",
        "difficulty": "MEDIUM",
        "question": "What does the CROSSFILTER function do?",
        "answer": "`CROSSFILTER` is used exclusively within a `CALCULATE` modifier. It allows you to programmatically change the cross-filtering direction of an existing physical relationship for that specific measure only (e.g., changing it from Single to Both, or disabling the relationship entirely by setting it to None)."
    },
    {
        "id": "medium-pbi-88",
        "category": "POWER BI",
        "niche": "DAX Advanced",
        "difficulty": "MEDIUM",
        "question": "What is the difference between VALUES and DISTINCT?",
        "answer": "Both functions return a single-column table of unique values. The key difference is how they handle the 'Blank Row' generated by referential integrity violations. `VALUES` includes the blank row if it exists (meaning the Fact table contains a key not found in the Dimension table). `DISTINCT` strips out the blank row, returning only the values physically present in the column."
    },
    {
        "id": "medium-pbi-89",
        "category": "POWER BI",
        "niche": "Visualizations",
        "difficulty": "MEDIUM",
        "question": "What are Calculation Groups in Power BI?",
        "answer": "Calculation Groups drastically reduce the number of redundant measures you have to write. Instead of creating [Sales YTD], [Profit YTD], and [Cost YTD], you create a single 'Time Intelligence' Calculation Group containing a 'YTD' item. You can then drop any base measure (Sales, Profit) into a visual and slice it by the Calculation Group to automatically apply the YTD logic dynamically."
    },
    {
        "id": "medium-pbi-90",
        "category": "POWER BI",
        "niche": "Visualizations",
        "difficulty": "MEDIUM",
        "question": "Explain the concept of 'Small Multiples'.",
        "answer": "Small Multiples is a formatting feature applied to standard charts (like Bar or Line charts). Instead of placing all categories onto a single cluttered chart, you drop a dimension into the 'Small Multiples' well. Power BI generates a grid of identical, smaller charts—one for each category—all sharing the same axis scale, making it incredibly easy to compare trends across categories visually."
    },
    {
        "id": "medium-adf-86",
        "category": "ADF",
        "niche": "Error Handling",
        "difficulty": "MEDIUM",
        "question": "How do you implement a 'Try-Catch' logic in ADF pipelines?",
        "answer": "ADF does not have a literal Try-Catch activity. Instead, you use activity dependency paths. You connect an activity to a subsequent 'Catch' activity (like an Email Alert or a Stored Procedure logging the error) using the red 'Upon Failure' path. You connect it to the next step of the pipeline using the green 'Upon Success' path."
    },
    {
        "id": "medium-adf-87",
        "category": "ADF",
        "niche": "Error Handling",
        "difficulty": "MEDIUM",
        "question": "What happens to a pipeline if an activity fails, but it has an 'Upon Failure' path defined?",
        "answer": "By default, if Activity A fails but triggers Activity B via an 'Upon Failure' path, and Activity B succeeds, ADF marks the entire Pipeline run as 'Succeeded' because the error was 'handled'. If you want the pipeline status to correctly reflect a failure, you must add a 'Fail Activity' at the very end of your error-handling path to explicitly terminate the pipeline with an error status."
    },
    {
        "id": "medium-adf-88",
        "category": "ADF",
        "niche": "Expression Language",
        "difficulty": "MEDIUM",
        "question": "How do you concatenate strings dynamically in ADF?",
        "answer": "You use the `@concat()` function in the dynamic content editor. For example, to generate a dynamic file path based on a pipeline parameter and the current date: `@concat(pipeline().parameters.FolderPath, '/', formatDateTime(utcnow(), 'yyyy-MM-dd'), '/data.csv')`."
    },
    {
        "id": "medium-adf-89",
        "category": "ADF",
        "niche": "Expression Language",
        "difficulty": "MEDIUM",
        "question": "What is the difference between utcnow() and adddays() functions?",
        "answer": "`@utcnow()` returns the current system timestamp in UTC format. `@adddays(timestamp, amount)` is used to add or subtract days from a given date. For example, to get yesterday's date, you would use `@adddays(utcnow(), -1)`."
    },
    {
        "id": "medium-adf-90",
        "category": "ADF",
        "niche": "Linked Services",
        "difficulty": "MEDIUM",
        "question": "What is the purpose of Parameterizing a Linked Service?",
        "answer": "Parameterization allows a single Linked Service to connect to multiple different databases or storage accounts dynamically at runtime. Instead of hardcoding the Database Name in the Linked Service, you define a parameter. When the pipeline runs, it passes the desired Database Name into the Linked Service. This reduces clutter by preventing the need to create 50 identical linked services for 50 databases."
    },
    {
        "id": "medium-adf-91",
        "category": "ADF",
        "niche": "Datasets",
        "difficulty": "MEDIUM",
        "question": "What is an 'Inline Dataset' in ADF Data Flows?",
        "answer": "Traditionally, you must create a Dataset artifact in the ADF UI and link it to your Data Flow source. An Inline Dataset allows you to define the source/sink properties (Linked Service, file path, format) directly inside the Data Flow canvas without creating a separate Dataset artifact in the repository. This keeps the workspace cleaner when dealing with hundreds of unique source files."
    },
    {
        "id": "medium-adf-92",
        "category": "ADF",
        "niche": "Triggers",
        "difficulty": "MEDIUM",
        "question": "What is an Event-based Trigger in ADF?",
        "answer": "Unlike a schedule trigger which runs at a specific time, an Event-based Trigger monitors an Azure Storage Account. It fires a pipeline run immediately when a specific event occurs, such as a new file (blob) being created or an existing file being deleted within a designated container. It relies on Azure Event Grid under the hood."
    },
    {
        "id": "medium-adf-93",
        "category": "ADF",
        "niche": "Triggers",
        "difficulty": "MEDIUM",
        "question": "What is a Custom Event Trigger?",
        "answer": "A Custom Event Trigger allows ADF to subscribe to custom topics in Azure Event Grid. Instead of just reacting to Azure Storage file creations, external applications can publish a completely custom JSON event payload to Event Grid (e.g., 'Customer Onboarded'). ADF will instantly intercept that custom event and trigger a pipeline, passing the JSON payload into pipeline parameters."
    },
    {
        "id": "medium-sql-76",
        "category": "SQL SERVER",
        "niche": "Indexes",
        "difficulty": "MEDIUM",
        "question": "What is a Filtered Index?",
        "answer": "A Filtered Index is a non-clustered index that includes a `WHERE` clause. It only indexes a subset of rows in the table. For example, `CREATE INDEX idx_Active ON Users (LastName) WHERE IsActive = 1`. This creates a much smaller, highly optimized index that saves disk space and maintenance overhead, perfect for queries that constantly filter for active/unprocessed records."
    },
    {
        "id": "medium-sql-77",
        "category": "SQL SERVER",
        "niche": "Indexes",
        "difficulty": "MEDIUM",
        "question": "Explain the concept of a Columnstore Index.",
        "answer": "Unlike traditional row-store indexes that store data row-by-row on a page, a Columnstore index stores data column-by-column. It heavily compresses the data, making it exceptionally fast for analytical (OLAP) queries where you need to aggregate massive amounts of data from a few specific columns (e.g., SUM of Sales). It performs poorly for singleton lookups or frequent updates."
    },
    {
        "id": "medium-sql-78",
        "category": "SQL SERVER",
        "niche": "Transactions",
        "difficulty": "MEDIUM",
        "question": "What is an Implicit vs Explicit Transaction?",
        "answer": "By default, SQL Server runs in Autocommit mode; every individual DML statement (INSERT, UPDATE) is an Implicit Transaction that is automatically committed upon success or rolled back on failure. An Explicit Transaction requires you to explicitly write `BEGIN TRAN`. All subsequent statements are grouped together, and nothing is finalized until you explicitly execute `COMMIT TRAN` or `ROLLBACK TRAN`."
    },
    {
        "id": "medium-sql-79",
        "category": "SQL SERVER",
        "niche": "Transactions",
        "difficulty": "MEDIUM",
        "question": "What is XACT_ABORT?",
        "answer": "When `SET XACT_ABORT ON` is executed at the top of a stored procedure, it alters error handling. If any severe run-time error occurs during an explicit transaction, SQL Server will immediately terminate the execution and automatically roll back the entire transaction. If it is OFF, the transaction might be left open (orphaned), causing massive blocking issues."
    },
    {
        "id": "medium-sql-80",
        "category": "SQL SERVER",
        "niche": "Isolation Levels",
        "difficulty": "MEDIUM",
        "question": "What is the Read Uncommitted isolation level, and what is its main risk?",
        "answer": "Read Uncommitted (often invoked via `WITH (NOLOCK)`) allows a query to read data that is currently being modified by another transaction but has not yet been committed. The main risk is a 'Dirty Read'; you might read data that the other transaction eventually rolls back, meaning your report is based on data that technically never existed in the database."
    },
    {
        "id": "medium-sql-81",
        "category": "SQL SERVER",
        "niche": "Isolation Levels",
        "difficulty": "MEDIUM",
        "question": "How does Snapshot Isolation solve blocking?",
        "answer": "When Snapshot Isolation is enabled, SQL Server uses row-versioning in TempDB. When Transaction A updates a row, it stores the old version in TempDB. If Transaction B wants to read that row before A commits, it doesn't get blocked (as it would in Read Committed). Instead, it reads the old, pre-update version from TempDB, ensuring viewers never block writers and writers never block viewers."
    },
    {
        "id": "medium-sql-82",
        "category": "SQL SERVER",
        "niche": "Query Optimization",
        "difficulty": "MEDIUM",
        "question": "What is Parameter Sniffing?",
        "answer": "When a stored procedure is executed for the first time, SQL Server 'sniffs' the parameter values passed and creates an execution plan optimized specifically for those values, caching it for reuse. Parameter sniffing becomes a severe problem if the first execution used an atypical value (e.g., retrieving 1 row) and created a plan that performs terribly for typical values (e.g., retrieving 1 million rows)."
    },
    {
        "id": "medium-sql-83",
        "category": "SQL SERVER",
        "niche": "Query Optimization",
        "difficulty": "MEDIUM",
        "question": "How do you fix Parameter Sniffing issues?",
        "answer": "You can append `OPTION (RECOMPILE)` to the query, forcing SQL Server to generate a new plan every single time based on the current parameters. Alternatively, you can use local variables inside the stored procedure, assigning the parameter value to the variable, which masks the value from the optimizer and forces it to create a generalized 'average' plan."
    },
    {
        "id": "medium-datalake-41",
        "category": "DATALAKE ARCHITECTURE",
        "niche": "Performance Tuning",
        "difficulty": "MEDIUM",
        "question": "What is the purpose of the V-Order feature in Microsoft Fabric?",
        "answer": "V-Order is a proprietary write-time optimization applied automatically to Parquet files in Fabric. It physically sorts and restructures the columnar data inside the file specifically to be uncompressed and read at blazing speed by the Power BI VertiPaq engine, bridging the gap between Data Lake storage and BI memory architecture."
    },
    {
        "id": "medium-datalake-42",
        "category": "DATALAKE ARCHITECTURE",
        "niche": "Performance Tuning",
        "difficulty": "MEDIUM",
        "question": "How does partitioning strategy impact query performance in a Data Lake?",
        "answer": "Partitioning creates hierarchical folders (e.g., `year=2024/month=01`). If queries frequently filter on 'year' and 'month', the engine only reads files in that specific folder, ignoring the rest of the lake (Partition Pruning). However, 'over-partitioning' by a high-cardinality column (like UserID) creates millions of tiny folders, which crushes performance because listing the directories takes longer than reading the data."
    },
    {
        "id": "medium-datalake-43",
        "category": "DATALAKE ARCHITECTURE",
        "niche": "Delta Lake Operations",
        "difficulty": "MEDIUM",
        "question": "What does the VACUUM command do in Delta Lake?",
        "answer": "Because Delta Lake uses Time Travel, when you UPDATE or DELETE data, it doesn't actually delete the old Parquet files immediately; it just marks them as obsolete in the log. Over time, this consumes massive storage. The `VACUUM` command physically deletes Parquet files that are no longer referenced by the latest transaction log state and are older than a specified retention threshold (default 7 days)."
    },
    {
        "id": "medium-datalake-44",
        "category": "DATALAKE ARCHITECTURE",
        "niche": "Delta Lake Operations",
        "difficulty": "MEDIUM",
        "question": "Can you Time Travel indefinitely in Delta Lake?",
        "answer": "No. Time Travel depends on the transaction log and the historical data files. By default, Delta retains history for 30 days. If you run `VACUUM` with a retention of 7 days, you physically delete files older than 7 days, meaning you permanently lose the ability to Time Travel back further than 7 days, regardless of what the log says."
    },
    {
        "id": "medium-datalake-45",
        "category": "DATALAKE ARCHITECTURE",
        "niche": "Integration",
        "difficulty": "MEDIUM",
        "question": "How does PolyBase relate to Data Lake Architecture?",
        "answer": "PolyBase is a technology built into SQL Server and Synapse Analytics. It allows you to write standard T-SQL queries that directly read Parquet or CSV files sitting externally in a Data Lake (via External Tables), effectively turning the relational database into a compute engine that can query unstructured lake data without importing it."
    },
    {
        "id": "medium-spark-46",
        "category": "SPARK & DATABRICKS",
        "niche": "Advanced DataFrames",
        "difficulty": "MEDIUM",
        "question": "What is the DataFrame API's window() function vs the SQL Window function?",
        "answer": "In PySpark, `pyspark.sql.functions.window` is specifically used for streaming aggregations. It groups timestamps into fixed intervals (e.g., tumbling or sliding windows) to count events over time. This is completely different from the SQL `pyspark.sql.Window` class, which is used for analytical ranking functions like `row_number()` or `lead()` over a partitioned set of rows."
    },
    {
        "id": "medium-spark-47",
        "category": "SPARK & DATABRICKS",
        "niche": "Advanced DataFrames",
        "difficulty": "MEDIUM",
        "question": "How do you define a UDF that returns a complex struct (Object) in PySpark?",
        "answer": "When defining a UDF, you must explicitly declare its return type using PySpark SQL Data Types. To return an object, you define a `StructType` containing multiple `StructField` definitions. You then pass this schema definition as the second argument to the `udf(my_func, returnType=schema)` registration function."
    },
    {
        "id": "medium-spark-48",
        "category": "SPARK & DATABRICKS",
        "niche": "Databricks Connect",
        "difficulty": "MEDIUM",
        "question": "What is Databricks Connect?",
        "answer": "Databricks Connect is a client library that allows developers to write PySpark, Scala, or R code in their local IDE (like VS Code or PyCharm) and execute that code directly on a remote Databricks cluster in the cloud. It sends the execution plan to the cluster, preventing the need to mock data locally, while allowing full local debugging and CI/CD integration."
    },
    {
        "id": "medium-spark-49",
        "category": "SPARK & DATABRICKS",
        "niche": "Data Science",
        "difficulty": "MEDIUM",
        "question": "What is MLflow in Databricks?",
        "answer": "MLflow is an open-source platform managed natively within Databricks for managing the end-to-end machine learning lifecycle. It tracks experiments (logging parameters, metrics, and models), packages code into reproducible runs, and provides a central Model Registry to manage the transition of models from Staging to Production APIs."
    },
    {
        "id": "medium-spark-50",
        "category": "SPARK & DATABRICKS",
        "niche": "Data Science",
        "difficulty": "MEDIUM",
        "question": "How do you distribute deep learning training across a Databricks cluster?",
        "answer": "Standard deep learning libraries (like TensorFlow or PyTorch) are designed to run on a single machine. In Databricks, you use libraries like HorovodRunner or spark-dl. These libraries take your single-machine deep learning code and automatically distribute the training payload (data and gradients) across all the worker nodes/GPUs in the Spark cluster."
    }
]

with open('/Users/santosh/.gemini/antigravity/scratch/fabric-pbi-prep/questions.js', 'r') as f:
    content = f.read()

json_str = json.dumps(new_batch, indent=2)
json_str = json_str[1:-1].strip()

if content.strip().endswith('];'):
    new_content = content.rsplit(']', 1)[0]
    if not new_content.strip().endswith('['):
        new_content += ",\n"
    new_content += json_str + "\n];\n"
    
    with open('/Users/santosh/.gemini/antigravity/scratch/fabric-pbi-prep/questions.js', 'w') as f:
        f.write(new_content)
    print("Batch 11 (88 questions) added successfully.")
